pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - status-success=Travis CI - Pull Request
      - status-success=typesafe-cla-validator
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
    actions:
      merge:
        method: merge
        strict: smart

  - name: backport patches to 2.7.x branch
    conditions:
      - merged
      - label=status:needs-backport
    actions:
      backport:
        branches:
          - 2.7.x
      label:
        remove: [status:needs-backport]

  - name: backport patches to 2.6.x branch
    conditions:
      - merged
      - label=status:needs-backport-2.6
    actions:
      backport:
        branches:
          - 2.6.x
      label:
        remove: [status:needs-backport-2.6]

  - name: forward patches to master branch
    conditions:
      - merged
      - label=status:needs-forwardport
    actions:
      backport:
        branches:
          - master
      label:
        remove: [status:needs-forwardport]

  - name: Delete the PR branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}

  - name: auto add wip
    conditions:
      # match a few flavours of wip
      - title~=^(\[wip\]( |:) |\[WIP\]( |:) |wip( |:) |WIP( |:)).*
    actions:
      label:
        add: ["status:block-merge"]
