#!/usr/bin/env bash

SCRIPTPATH="${BASH_SOURCE[0]}";
if ([ -L "${SCRIPTPATH}" ]) then
  while([ -h "${SCRIPTPATH}" ]) do SCRIPTPATH=`readlink "${SCRIPTPATH}"`; done
fi
pushd . > /dev/null
cd `dirname $0`
cd `dirname ${SCRIPTPATH}` > /dev/null
SCRIPTPATH=`pwd -P`;
popd > /dev/null


if [ -f conf/application.yml ]
then
	$SCRIPTPATH/framework/build play "$@"
else
	java -cp $SCRIPTPATH/framework/sbt/boot/scala-2.9.0/lib/*:$SCRIPTPATH/framework/sbt/boot/scala-2.9.0/org.scala-tools.sbt/sbt/0.10.1/*:$SCRIPTPATH/repository/play/play_2.9.0/2.0/jars/* play.console.Console "$@"
fi
