#! /usr/bin/env sh

if [ -f conf/application.conf ]; then
  if test "$1" = "clean"; then
    `dirname $0`/framework/cleanIvyCache
  fi
  if test "$1" = "stop"; then
    if [ -f RUNNING_PID ]; then
      echo "[info] Stopping application (with PID `cat RUNNING_PID`)..."
      kill `cat RUNNING_PID`

      RESULT=$?

      if test "$RESULT" = 0; then
        echo "[info] Done!"
        exit 0
      else
        echo "[\033[31merror\033[0m] Failed ($RESULT)"
        exit $RESULT
      fi
    else
      echo "[\033[31merror\033[0m] No RUNNING_PID file. Is this application running?"
      exit 1
    fi
  fi
  if [ -n "$1" ]; then
    `dirname $0`/framework/build "$@"
  else
    `dirname $0`/framework/build play
  fi
else
  if [ -L $0 ]; then
    frameworkpath=`dirname $0`/`readlink $0`
    frameworkpath=`dirname $frameworkpath`
  else
    frameworkpath=`dirname $0`
  fi
  java -Dsbt.ivy.home=$frameworkpath/repository -Dplay.home=$frameworkpath/framework -Dsbt.boot.properties=$frameworkpath/framework/sbt/play.boot.properties -jar $frameworkpath/framework/sbt/sbt-launch-0.11.0.jar "$@"
fi
