package play.mvc;

/**
 * Define a Call, describing an HTTP request. For example used to create links or fill redirect data.
 *
 * These values are usually generated by the reverse router.
 */
public interface Call {
    
    /**
     * The request URL.
     */
    public String url();
    
    /**
     * The request HTTP method.
     */
    public String method();
    
}