# Initial test schema for users db

# --- !Ups

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    username varchar(255) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO users VALUES (1, 'Player1');

# --- !Downs

DROP TABLE users;
