#! /usr/bin/env sh

echo "[info] Cleaning target directories..."

rm -rf `dirname $0`/target
rm -rf `dirname $0`/project/project
rm -rf `dirname $0`/project/target
rm -rf `dirname $0`/logs
rm -rf `dirname $0`/src/anorm/target
rm -rf `dirname $0`/src/play/target
rm -rf `dirname $0`/src/templates/target
rm -rf `dirname $0`/src/sbt-plugin/target
rm -rf `dirname $0`/src/console/target
rm -rf `dirname $0`/sbt/boot/scala-2.9.1/play