#! /usr/bin/env sh

if [ -z "${VERSION}" ]; then
  VERSION="2.0-RC1-SNAPSHOT"
fi

`dirname $0`/cleanEverything
`dirname $0`/build -Dversion=${VERSION} build-repository api-docs

rm -rf /tmp/play-*

echo "[info] Copying to /tmp/play-${VERSION}..."
cp -rf `dirname $0`/.. /tmp/play-${VERSION}

cd /tmp

echo "[info] zipping..."
zip -9 -r play-${VERSION}.zip play-${VERSION} -x '*.git/*' '*.lock' '*.history' 'play-${VERSION}/.gitmodules' 'play-${VERSION}/.gitignore' '*.DS_Store' 'play-${VERSION}/dist/*' '*/target/*' 'play-${VERSION}/framework/sbt/boot/*' 'play-${VERSION}/repository/cache/*' '*/logs/*' '*/project/project/*' '*.log'

rm -rf /tmp/play-${VERSION}

echo "[info] Package is available at /tmp/play-${VERSION}.zip"