#! /bin/bash

# Copyright (C) 2009-2015 Typesafe Inc. <http://www.typesafe.com>

set -e
export CURRENT=`pwd`
export SCRIPT=`dirname "$0"`

cd "$SCRIPT"
export BUILD=`pwd`/build

CROSSBUILD=

if [ "$1" == + ]
then
    CROSSBUILD=+
    shift
fi

echo "[info]"
echo "[info] ---- BUILDING PLAY "
echo "[info]"
$BUILD "$@" ${CROSSBUILD}publishLocal

echo "[info]"
echo "[info] ---- PLAYFRAMEWORK CORE TEST RUNNER"
echo "[info]"

$BUILD "$@" ${CROSSBUILD}test

echo "[info]"
echo "[info] ---- SCRIPTED TESTS"
echo "[info]"

$BUILD "$@" scripted

if [ -n "$CROSSBUILD" ]
then
    $BUILD "$@" "set scalaVersion in PlayBuild.PlayProject := \"2.11.5\"" scripted
fi

rm -rf ./logs

cd $CURRENT

echo "[info]"
echo "[info] ---- RUNNING DOCUMENTATION TESTS"
echo "[info]"

cd ../documentation
$BUILD "$@" clean ${CROSSBUILD}test evaluateSbtFiles validate-docs
cd $CURRENT

echo "[info]"
echo "[info] ---- TESTING TEMPLATES"
echo "[info]"

cd ../templates
$BUILD "$@" ${CROSSBUILD}testTemplates
cd $CURRENT

echo "[info]"
echo "[info] ALL TESTS PASSED"
echo "[info]"
