#! /usr/bin/env sh

# Copyright (C) 2009-2013 Typesafe Inc. <http://www.typesafe.com>

set -e

./build clean scalariformFormat
git diff --exit-code || (
  echo "ERROR: Scalariform check failed, see differences above."
  echo "To fix, format your sources using ./build scalariformFormat before submitting a pull request."
  echo "Additionally, please squash your commits (eg, use git commit --amend) if you're going to update this pull request."
  false
)

./runtests
