#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$BASEDIR"

printMessage "CLEANING IVY LOCAL REPO AND CACHE"
rm -rf $HOME/.ivy2/local
rm -rf $HOME/.ivy2/cache/com.typesafe.play/*
rm -rf $HOME/.ivy2/cache/scala_*/sbt_*/com.typesafe.play/*
find $HOME/.ivy2 -name "ivydata-*.properties" -delete
printMessage "CLEANED IVY LOCAL REPO AND CACHE"

printMessage "CROSS-PUBLISHING PLAY LOCALLY FOR SBT SCRIPTED TESTS"
runSbt +publishLocal
printMessage "CROSS-PUBLISHED PLAY LOCALLY FOR SBT SCRIPTED TESTS"
