#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$BASEDIR"
start test "RUNNING IT TESTS FOR SCALA 2.13"
runSbt Play-Integration-Test/it:test
end test "ALL IT TESTS PASSED"
