#!/usr/bin/env bash

set -o pipefail

declare -r scalafmt_version="2.0.0-RC5"

die() { echo "Aborting: $*"; exit 1; }

COURSIER=coursier
if ! command -v $COURSIER > /dev/null 2>&1; then
  COURSIER="$HOME/.coursier/coursier"
  if ! command -v $COURSIER > /dev/null 2>&1; then
    mkdir -p $(dirname "$COURSIER") || die "Failed to create $(dirname "$COURSIER")"
    curl -Lo "$COURSIER" https://git.io/coursier-cli || die "Failed to download coursier"
    chmod +x "$COURSIER"
  fi
fi

"$COURSIER" launch org.scalameta:scalafmt-cli_2.12:$scalafmt_version -- "$@"
