#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

SCALA_VERSION=$1
shift

cd "$BASEDIR"

start test "RUNNING TESTS FOR SCALA $SCALA_VERSION"

runSbt "++${SCALA_VERSION} test"

end test "ALL TESTS PASSED"
