#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

SCALA_VERSION="2.12.8"
SBT_VERSION="1.2.8"

cd "$BASEDIR"

printMessage "PUBLISHING PLAY LOCALLY FOR SBT ${SBT_VERSION}"
runSbt ++${SCALA_VERSION} quickPublish publishLocal

printMessage "RUNNING SCRIPTED TESTS FOR SBT ${SBT_VERSION}"
runSbt scripted

printMessage "ALL SCRIPTED TESTS PASSED"
