#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$DOCUMENTATION"

printMessage "RUNNING DOCUMENTATION TESTS"
runSbtWithSnapshots test
printMessage "ALL DOCUMENTATION TESTS PASSED"
