#!/usr/bin/env bash

# Copyright (C) 2009-2019 Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

SBT_VERSION="${1:-1.x}"
shift
setScalaVersionFromSbtVersion

cd "$BASEDIR"

start scripted "RUNNING SCRIPTED TESTS FOR SBT $SBT_VERSION"
runSbt "++$SCALA_VERSION" "Sbt-Plugin/scripted $@"
end scripted "ALL SCRIPTED TESTS PASSED"
