#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$BASEDIR"

printMessage "RUNNING TESTS FOR SCALA 2.11"

runSbt "++2.11.12 test"

printMessage "ALL TESTS PASSED"
