#!/usr/bin/env bash

# Copyright (C) 2009-2018 Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

SCALA_VERSION="2.10.6"
SBT_VERSION="0.13"

cd "$BASEDIR"

printMessage "PUBLISHING PLAY LOCALLY FOR SBT ${SBT_VERSION}"
runSbtNoisy quickPublish publishLocal

printMessage "RUNNING SCRIPTED TESTS FOR SBT ${SBT_VERSION}"
runSbtNoisy "++${SCALA_VERSION} scripted"

printMessage "ALL SCRIPTED TESTS PASSED"
