#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

SCALA_VERSION=$1

if [ -z $SCALA_VERSION ]; then
  echo "You need to pass the Scala version as argument to this script"
  exit 1
fi

shift

cd "$DOCUMENTATION"

start test "RUNNING DOCUMENTATION TESTS FOR SCALA $SCALA_VERSION"
runSbt "++${SCALA_VERSION} test"
end test "ALL DOCUMENTATION TESTS PASSED"
