#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$BASEDIR"

printMessage "RUNNING TESTS FOR SCALA 2.12"

runSbt "test"

printMessage "ALL TESTS PASSED"
