#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$BASEDIR"

start test "RUNNING TESTS FOR SCALA 2.12"

runSbt "++2.12.11 test"

end test "ALL TESTS PASSED"
