#!/usr/bin/env bash

# Copyright (C) Lightbend Inc. <https://www.lightbend.com>

# shellcheck source=scripts/scriptLib
. "$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/scriptLib"

cd "$BASEDIR"

scalafmtValidation "framework"
javafmtValidation "framework"


start mima "VALIDATE BINARY COMPATIBILITY"
runSbt +mimaReportBinaryIssues
end mima "VALIDATED BINARY COMPATIBILITY"


start headerCheck "VALIDATE FILE LICENSE HEADERS"
runSbt +headerCheck +test:headerCheck Play-Microbenchmark/test:headerCheck
end headerCheck "VALIDATED FILE LICENSE HEADERS"
